### ISSUE TITLE
Do not call System.exit()

### ISSUE THREAD

**Issue by sarychuk** [cmput402w2016/Team-3--Kaleidoscope#10]
2 defects in 1 file. Reliability Fix.

**Comment by timoteialbu** [comment]
This is a strange error from Kiuwan.
According to this http://stackoverflow.com/a/3716015 and others, sometimes the best way to quit a large program is by doing a System.exit(<SPECIAL CODE>). its not good to exit without a code, but when a code exists its fine. In our case, having to fix this file which is part of VLC is to difficult since we don't know then entire projects logic. If we would want to throw an error instead, we would have to catch it somewhere. We also would need to cleanup all the resources and have a way to get back to the main function. So it can't be done
